### ISSUE TITLE
"A stop job is running for Service for snap application lxd.daemon" running for 10 minutes at shutdown

### ISSUE THREAD

**Issue by AceSlash** [lxc/lxd-pkg-snap#39] opened 2019-10-29 11:03 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info":
```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.36.98.8:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    -----END CERTIFICATE-----
  certificate_fingerprint: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 4.15.0-66-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: srv-308
  server_pid: 3952
  server_version: "3.18"
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.6
```
   * Storage backend in use: ZFS

# Issue description

At shutdown, the message `A stop job is running for Service for snap application lxd.daemon` runs until its time out of 10 minutes.

This issue has been reproduced on a series of 10 identical servers, mainly during their initialization that includes several reboot. There was no container running on them.

# Steps to reproduce

 1. Install lxd from snap
 2. Reboot or shudown

![snap_lxd_daemon](https://user-images.githubusercontent.com/5392990/67761730-2d863100-fa44-11e9-8d16-260cd37e79d4.png)

**Comment by stgraber** [comment] 2019-10-30 12:26
Deployed 18.04 with the same kernel as you do, installing the stable snap, ran init with zfs and rebooted, nothing hung in this case.

So going to have to be a bit more creative to try and get something to act like your system.

**Comment by harridu** [comment] 2019-11-07 10:58
I have the same problem on Buster. For testing I have backported snapd 2.42. During upgrade time I noticed a long delay, too. Not sure if its related, though. "ps -ef --forest" shows
~~~
hdunkel     2990    2970  0 08:24 tty1     00:00:00                  \_ xterm -g 80x40+0+148 -n dpcl082.ac.aixigo.de -j
hdunkel     3004    2990  0 08:24 pts/5    00:00:00                  |   \_ bash
root      214624    3004  0 11:49 pts/5    00:00:00                  |       \_ su
root      214701  214624  0 11:49 pts/5    00:00:00                  |           \_ bash
root      214714  214701  2 11:49 pts/5    00:00:04                  |               \_ aptitude
root      217153  214714  0 11:51 pts/10   00:00:00                  |                   \_ /usr/bin/dpkg --status-fd 64 --configure --pending
root      217154  217153  0 11:51 pts/10   00:00:00                  |                       \_ /bin/sh /var/lib/dpkg/info/snapd.postinst configure 2.37.4-1+b1
root      217195  217154  0 11:51 pts/10   00:00:00                  |                           \_ /bin/systemctl start snapd.seeded.service snapd.service snapd.socket
root      217202  217195  0 11:51 pts/10   00:00:00                  |                               \_ /bin/systemd-tty-ask-password-agent --watch
~~~
Of course there is no password dialog.

**Comment by bbock** [comment] 2019-11-15 11:26
Same issue here on an Ubuntu 19.04 with Ubuntu stock snapd version `2.40+19.04`.
lxd snap version `3.18 rev 12317` with `dir` storage and no containers.

From the journal:
```
Nov 15 12:15:34 ubuntu systemd[1]: snap.lxd.daemon.service: Stopping timed out. Terminating.
Nov 15 12:15:34 ubuntu systemd[1]: snap.lxd.daemon.service: Control process exited, code=killed, status=15/TERM
Nov 15 12:15:34 ubuntu systemd[1]: snap.lxd.daemon.service: Failed with result 'timeout'.
Nov 15 12:15:34 ubuntu systemd[1]: Stopped Service for snap application lxd.daemon.
```

The commands `lxd shutdown` and `snap restart lxd` hang as well.

**Comment by bbock** [comment] 2019-11-15 12:10
Additional information:

While waiting for a timeout, a process `lxd shutdown` is running. Killing that process immediately finishes the shutdown.

Stracing this suspicious `lxd shutdown` gives not a lot info , but it is waiting for a futex:

```
strace: Process 2841 attached
futex(0x1f418c8, FUTEX_WAIT_PRIVATE, 0, NULL
```

**Comment by stgraber** [comment] 2019-11-15 17:17
Thanks, that's good to know.

I'm sorry I didn't make more progress on this yet, I've been traveling quite a bit over the past few weeks and only poking at this a bit here and there. The lack of an easy reproducer on my end is also making debugging slightly harder than it could be.

**Comment by AceSlash** [comment] 2019-11-15 18:57
I noticed that last few days that I now have the same issue on my Fedora 30 laptop, which is a lot more troublesome as I shutdown it much more often. I have to power it off forcefully so unfortunately the `journalctl -b -1` stops before the interesting part.

Once again, I have no container running during the wait time (I only start them when I need, and usually stop them during the day, before the shutdown of my laptop itself).

I'll try to update my laptop to Fedora 31, see if it changes anything.

**Comment by stgraber** [comment] 2019-11-15 19:50
@AceSlash can you check if the LXD daemon is running at the time you shutdown?

Since the daemon is socket activated, it may not be, which would give me some pointers on what may be wrong.

Effectively do `ps aux | grep lxd` and see if the daemon is running, if not and the shutdown hangs, that'd be a useful data point.

**Comment by AceSlash** [comment] 2019-11-15 21:25
Looks like it's running:
```
root@lpt-064:~ # ps aux | grep lxd
root      3247  0.0  0.0   4500  1680 ?        Ss   19:22   0:00 /bin/sh /snap/lxd/12317/commands/daemon.start
root      3439  0.0  0.0  95436  1392 ?        Sl   19:22   0:00 lxcfs /var/snap/lxd/common/var/lib/lxcfs -p /var/snap/lxd/common/lxcfs.pid
root      3448  0.0  0.5 993756 82188 ?        Sl   19:22   0:05 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root      7200  0.0  0.0 215744   824 pts/0    S+   22:21   0:00 grep --color=auto lxd
root@lpt-064:~ # lxc list
+------------------+---------+------+------+------------+-----------+
|       NAME       |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------------------+---------+------+------+------------+-----------+
| centos-7-xxxxxxx | STOPPED |      |      | PERSISTENT | 0         |
+------------------+---------+------+------+------------+-----------+
| xxxxxxxxxx-api   | STOPPED |      |      | PERSISTENT | 0         |
+------------------+---------+------+------+------------+-----------+
root@lpt-064:~ # snap list
Name     Version                  Rev    Tracking  Publisher   Notes
core     16-2.42.1                8039   stable    canonical✓  core
lxd      3.18                     12317  stable    canonical✓  -
spotify  1.1.10.546.ge08ef575-19  36     stable    spotify✓    -
```
It's pretty late here so I may not be able to answer until Monday, I'll stop now and if it doesn't hang, I'll restart to tell you, if not, it means that it hanged for 10 minutes :-p

**Comment by AceSlash** [comment] 2019-11-15 21:33
Damn, it did stop instantly this time :-/ It didn't for my last 3 poweroff at least. When I left the office sooner today, it did hang.

**Comment by stgraber** [comment] 2019-11-15 21:35
Ok, so it was running, I'm wondering where the case it hangs is if it wasn't running at the time the system got shutdown.

**Comment by mispp** [comment] 2019-11-23 15:52
not sure if this is relevant anymore, but same thing happens on fedora 31 (fresh) install with btrfs backend storage.

**Comment by stgraber** [comment] 2019-11-25 18:14
I couldn't really reproduce the issue but I see how a race in systemd could get things to hang so changed the logic to something which doesn't depend on the unix socket, hopefully that takes care of it.

**Comment by couteau** [comment] 2019-12-01 00:27
I've got the same issue as of today on Ubuntu 19.10 with a zfs pool for lxd and zfs as the root fs . Not sure if your fix has been released.

**Comment by stgraber** [comment] 2019-12-01 02:02
It hasn't yet, we'll update the stable snap on Monday.

**Comment by shuhaowu** [comment] 2020-02-18 15:19
Is it possible to customize the timeout? I'm seeing this issue even without a container created on a bionic machine.

**Comment by mazerty** [comment] 2020-03-02 20:04
i'm having this issue with a fresh 18.04.4 install, with snap packaging :(

**Comment by claytondukes** [comment] 2020-03-09 16:56
Same problem here with an upgrade from 18.04.4 to 19.10.

FWIW, I can't, for the life of me, understand why systemd doesn't default to at least *some* timeout. We see the same issues for other tools and even network connections when a NIC is not connected. This make zero sense. Timeouts mean not having to force a system shutdown the hard way.

**Comment by dulinux** [comment] 2020-03-11 23:22
Same thing here with Ubuntu 18.04 and snap lxd version 3.21

![IMG_20200311_201616](https://user-images.githubusercontent.com/539696/76472786-4da40480-63d5-11ea-8ba7-1e82a1408c79.jpg)

**Comment by blowoffsteam81** [comment] 2020-03-13 01:30
I can confirm this as well. It happens to me on Ubuntu 18.04 and also snap lxd version 3.2.2
Stroage backend is ZFS. Difference for me is that my systems reboots without normaly when i 
lxc stop my containers before rebooting.

**Comment by stgraber** [comment] 2020-03-13 02:28
`journalctl -b -1 -n 500` following the reboot may be useful to get a view of what was going on during shutdown.

**Comment by dulinux** [comment] 2020-03-13 11:54
> 
> 
> `journalctl -b -1 -n 500` following the reboot may be useful to get a view of what was going on during shutdown.

Sorry, I can´t provide the output because it´s not happening anymore. I´m almost sure it was some network related problem. I was working with a dual NIC netplan configuration and to be honest although it was working I later realized it had some issues. After converting the netplan configuration to a bond with a bridge and VLANs, the shutdown process was smooth. So I encourage everyone in the thread to double check you network configuration.

Thank you.

**Comment by blowoffsteam81** [comment] 2020-03-13 15:44
I reinstalled LTS 18.04 and switched to the snap lxd version immediately after.
So far i couldn`t reproduce the reboot problem. If it happens again i ll let you know and provide additional informations.

**Comment by blowoffsteam81** [comment] 2020-03-13 20:24
Ok, it happened again today and i could figure out that this only seems to happen when 
i enable the ufw firewall.
journalctl -b -1 -n 500 shows a lot of [UFW BLOCK] messages in the reboot/shutdown procedure, right before the 10minute timeout occurs. It doesn`t happen all the time though.
I hope this helpful.

**Comment by dulinux** [comment] 2020-03-14 05:20
> 
> 
> `journalctl -b -1 -n 500` following the reboot may be useful to get a view of what was going on during shutdown.

Ok, it has happened again. So I decided to install a clean testing Ubuntu Server on another physical machine. The problem persists. I don´t have ZFS in this one. Networking is pretty simple.

I have instanciated two containers using macvlan, one with each ethernet card as parent.

This is my netplan config:

```
g@utest:~$ cat /etc/netplan/01-netcfg.yaml
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: no
      dhcp6: no
      addresses:
      - 192.168.18.5/24
      gateway4: 192.168.18.1
      nameservers:
        addresses:
        - 9.9.9.9
        - 8.8.8.8
      routes:
      - to: 192.168.40.0/24
        via: 192.168.40.1
    enp5s0:
      dhcp4: no
      dhcp6: no
      addresses:
      - 192.168.40.5/24

```

Attached is the result of journalctl -b -1 -n 500 after the (long) reboot.
[journalctl-log.txt](https://github.com/lxc/lxd-pkg-snap/files/4332312/journalctl-log.txt)

Please, point me any other info I could provide.

Thank you.

**Comment by dulinux** [comment] 2020-03-15 17:04
Okay, it has happened again. It is indeed ramdom. My network configuration is okay now and the 10 minutes wait happend anyway. I don´t have any firewall configued in this box.

**Comment by NeonHorizon** [comment] 2020-03-17 09:20
Just had this happen here as well. Rebooted four identical Ubuntu 18.04 servers with the snap version of LXD, one of them got stuck the others were OK.

**Comment by isolin** [comment] 2020-03-31 00:29
Happens to me quite often as well. Sometimes it hangs for a few minutes and terminates earlier, sometimes it gets killed after the 10 mins interval.

**Comment by stgraber** [comment] 2020-03-31 00:35
A few minutes and terminating, if you have running containers, that'd be the normal behavior.

LXD sends a signal to init in all the containers, containers then go through their shutdown process, if you have some of those also failing to shutdown for some reason or needing to flush a lot of data to disk, delays can add up.

The real issue is if you're hitting the 10min shutdown timeout when you don't have any running containers or LXD itself wasn't even running.

**Comment by isolin** [comment] 2020-03-31 00:43
This is my `journalctl` output of the timeout:
[ten-minutes.log](https://github.com/lxc/lxd-pkg-snap/files/4406107/ten-minutes.log)

**Comment by isolin** [comment] 2020-03-31 00:46
@stgraber I have just one container on this machine. It was probably running. However, it is a clean and fresh install of `ubuntu-minimal:bionic`. That should not be an issue, I suppose.

**Comment by stgraber** [comment] 2020-03-31 01:10
Yeah, it's kinda frustrating that there is no straightforward reproducer for this.
We have VMs here where we could easily still login while shutdown is stuck so could easily poke around, but we've never gotten one of those to hang...

Just now I was fixing some other snap issues and did a solid dozen reboots of a system that matches your description without it hanging once.

What storage backend are you using?

**Comment by mazerty** [comment] 2020-03-31 04:43
i'm using zfs as backend
i would add that i switched back to the debian package and there's no issue there
could it be only related to the snap packaging ?

**Comment by NeonHorizon** [comment] 2020-03-31 07:53
I'm using BTRFS and seeing it.

**Comment by isolin** [comment] 2020-03-31 16:12
For me it's zfs. Is there a way to get more detailed information? If so please tell me how and I will try to provide it.

I also noticed this behavior only with the snap installation.

**Comment by stgraber** [comment] 2020-03-31 16:54
You could try doing `snap set lxd daemon.debug=true` followed by `systemctl reload snap.lxd.daemon`
And then after the next time you hit the problem, grab the content of `/var/snap/lxd/common/lxd/logs`, you'll most likely want .1 for the one showing the previous shutdown.

**Comment by stgraber** [comment] 2020-04-03 21:23
I've just added a ton of extra logging to the edge snap, will make sure things behave and then add that to candidate and stable too.

**Comment by stgraber** [comment] 2020-04-03 22:34
Should look something like this:
```
Apr 03 22:33:46 bionic systemd[1]: Stopping Service for snap application lxd.daemon...
Apr 03 22:33:46 bionic lxd.daemon[1805]: => Stop reason is: host shutdown
Apr 03 22:33:46 bionic lxd.daemon[1805]: => Stopping LXD (with container shutdown)
Apr 03 22:33:47 bionic lxd.daemon[1805]: ==> Stopped LXD
Apr 03 22:33:47 bionic lxd.daemon[1805]: => Stopping LXCFS
Apr 03 22:33:47 bionic lxd.daemon[1805]: ==> Stopped LXCFS
Apr 03 22:33:47 bionic lxd.daemon[1805]: => Cleaning up PID files
Apr 03 22:33:47 bionic lxd.daemon[1805]: => Cleaning up namespaces
Apr 03 22:33:47 bionic lxd.daemon[1805]: => All done
Apr 03 22:33:48 bionic systemd[1]: Stopped Service for snap application lxd.daemon.
```

But also log anything that actually fails.

**Comment by stgraber** [comment] 2020-04-03 22:38
Pushing to candidate now, that snap should be done building in about 2h and will have the extra logging. Stable users will get it on Monday.

**Comment by stgraber** [comment] 2020-04-07 20:53
So had a bit of a breakthrough on this one thanks to LXD VMs and our agent not liking to die early :)

I effectively managed to keep a shell on a system with the issue, the result is a process list like this one:

```
root         1  0.1  0.0 161464  8680 ?        Ss   17:30   0:18 /sbin/init
root       262  0.0  0.0  26296  8384 ?        S<s  17:30   0:00 /lib/systemd/systemd-journald
root       279  0.0  0.0  14476  3644 ?        Ss   17:30   0:02 /lib/systemd/systemd-udevd
systemd+   300  0.0  0.0  11636  5176 ?        Ss   17:30   0:00 /lib/systemd/systemd-networkd
systemd+   410  0.0  0.0  10436  4228 ?        Ss   17:30   0:00 /lib/systemd/systemd-resolved
systemd+   411  0.0  0.0  83752  2512 ?        Ssl  17:30   0:00 /lib/systemd/systemd-timesyncd
root       412  0.0  0.1 1823860 17352 ?       Ssl  17:30   0:09 /run/lxd_config/9p/lxd-agent
root     10716  0.0  0.0   8468  3400 pts/0    Ss   20:28   0:00  \_ bash
root     10891  0.0  0.0  10420  3236 pts/0    R+   20:34   0:00      \_ ps fauxww
message+   419  0.0  0.0   6980  4076 ?        Ss   17:30   0:03 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root      7104  0.0  0.0   7680  4448 ?        Ss   18:01   0:00 /usr/sbin/haveged --Foreground --verbose=1 -w 1024
root      7777  0.0  0.0  77944  1096 ?        Ss   18:02   0:00 /sbin/lvmetad -f
root      7707  0.0  0.0   1872  1272 ?        Ss   18:36   0:00 /bin/sh /snap/lxd/14335/commands/daemon.start
root      7863  0.0  0.3 1631048 47756 ?       Sl   18:36   0:03  \_ lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
lxd       8189  0.0  0.0   6940  3028 ?        Ss   18:36   0:00      \_ dnsmasq --keep-in-foreground --strict-order --bind-interfaces --except-interface=lo --no-ping --interface=lxdbr0 --quiet-dhcp --quiet-dhcp6 --quiet-ra --listen-address=10.0.3.1 --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases --dhcp-hostsfile=/var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts --dhcp-range 10.0.3.2,10.0.3.254,1h --listen-address=2001:470:b368:4242::1 --enable-ra --dhcp-range ::,constructor:lxdbr0,ra-stateless,ra-names -s lxd -S /lxd/ --conf-file=/var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.raw -u lxd
root      7858  0.0  0.0  85040  1232 ?        Sl   18:36   0:00 lxcfs /var/snap/lxd/common/var/lib/lxcfs -p /var/snap/lxd/common/lxcfs.pid
root     10729  0.4  0.1 1282204 20464 ?       Ssl  20:28   0:01 /usr/bin/snap run --command=stop lxd.daemon
```

Note the last command which is what systemd started to stop LXD.

This command is stuck in the `snap` command, not in any of our logic. It appears to be trying to connect to the snapd socket, which is no longer reachable as snapd itself has been stopped already...

I've reached out to the snapd team to have them look into this because well, it may not be something we can control at all and may be a bug in the `snap run` command or an issue with systemd unit ordering.

**Comment by stgraber** [comment] 2020-04-07 20:54
@zyga

**Comment by stgraber** [comment] 2020-04-08 19:34
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1871652 is the upstream bug report and has all the details captured so far for the source of the hang.

Closing our side of this as there's nothing to change on the LXD snap side, we'll need an updated snapd to be pushed out to users.

**Closed by stgraber** 2020-04-08 19:34 UTC
Labels: Bug

**Comment by dired** [comment] 2020-04-09 09:18
hate so say
